name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # Додатково: Тести, якщо є
    # - name: Run tests
    #   run: npm test

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: task-manager
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
